#!/usr/bin/env python3
# =============================================================================
# TTL2Cypher.py
# Author:  Kent Stroker
# Date:    2026-03-09
#
# Converts RDF/Turtle (.ttl) files generated by FamilyTreeDataGeneratorV2.py
# into idempotent Neo4j Cypher statements. Uses a hand-rolled regex parser
# tightly coupled to the TTL output format of the generator. Emits MERGE-based
# Cypher for Person nodes with PARENT_OF and MARRIED_TO relationships.
# Also generates CSV files for bulk loading via Neo4j's LOAD CSV mechanism.
#
# Usage:
#   python3 TTL2Cypher.py --data-dir out_graphdb/data --out out_graphdb --split --csv
#
#   --data-dir  Directory containing generated *.ttl files
#   --out       Output directory (split/csv mode) or file path (combined mode)
#   --split     Write one data-NNN.cypher per TTL file (recommended for Neo4j Browser)
#   --csv       Also emit persons.csv, parent_of.csv, married_to.csv, loadFromCSV.cypher
# =============================================================================
from __future__ import annotations

import argparse
import csv
import glob
import io
import os
import re
import sys
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Set, Tuple


EX = "http://example.org/family/"


@dataclass
class Person:
    pid: str  # e.g. "0-5" (sample_index-local_id)
    given_name: Optional[str] = None
    surname: Optional[str] = None
    full_name: Optional[str] = None
    female: Optional[bool] = None
    date_of_birth: Optional[str] = None  # YYYY-MM-DD
    date_of_death: Optional[str] = None  # YYYY-MM-DD



_TTL_PREFIX_RE = re.compile(r"^\s*@prefix\s+([A-Za-z][\w\-]*)\s*:\s*<([^>]+)>\s*\.\s*$")
_IRI_RE = re.compile(r"<([^>]+)>")
_LITERAL_RE = re.compile(r"\"((?:\\.|[^\"])*)\"")  # basic "..." with backslash escapes
_DATE_TYPED_RE = re.compile(r"\"(\d{4}-\d{2}-\d{2})\"\s*\^\^\s*xsd:date")


def _unescape_ttl_string(s: str) -> str:
    # Matches the escaping done in ttl_str() in your generator.
    return (
        s.replace("\\\\", "\\")
        .replace('\\"', '"')
    )


def _parse_person_id(iri: str) -> Optional[str]:
    # expects http://example.org/family/person/<sample>-<id>
    if not iri.startswith(EX):
        return None
    rest = iri[len(EX):]
    if not rest.startswith("person/"):
        return None
    return rest.split("/", 1)[1]



def _split_outside_quotes(s: str, sep: str) -> List[str]:
    # splits by sep but ignores seps inside "..."
    out: List[str] = []
    buf: List[str] = []
    in_q = False
    esc = False
    for ch in s:
        if esc:
            buf.append(ch)
            esc = False
            continue
        if ch == "\\" and in_q:
            buf.append(ch)
            esc = True
            continue
        if ch == '"':
            in_q = not in_q
            buf.append(ch)
            continue
        if (not in_q) and ch == sep:
            out.append("".join(buf))
            buf = []
        else:
            buf.append(ch)
    out.append("".join(buf))
    return out


def _normalize_ws(s: str) -> str:
    return " ".join(s.strip().split())


def parse_ttl_files(paths: Iterable[str]) -> Tuple[Dict[str, Person], Set[Tuple[str, str]], Set[Tuple[str, str]]]:
    """
    Returns:
      people_by_id,
      parent_of_edges: set[(parent_id, child_id)],
      married_to_edges: set[(a_id, b_id)],
    """
    people: Dict[str, Person] = {}
    parent_of: Set[Tuple[str, str]] = set()
    married_to: Set[Tuple[str, str]] = set()

    for path in paths:
        with open(path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        lines = [ln.rstrip("\n") for ln in lines]

        i = 0
        while i < len(lines):
            line = lines[i].strip()
            if not line or line.startswith("#"):
                i += 1
                continue
            if line.startswith("@prefix"):
                i += 1
                continue

            # Multi-line block: starts with "<...> ... ;" and ends with "."
            if line.startswith("<") and (";" in line) and (not line.endswith(".")):
                block_lines = [line]
                i += 1
                while i < len(lines):
                    block_lines.append(lines[i].strip())
                    if lines[i].strip().endswith("."):
                        break
                    i += 1
                block = " ".join(block_lines)
                subj_match = _IRI_RE.match(block.strip())
                if not subj_match:
                    i += 1
                    continue
                subj_iri = subj_match.group(1)

                pid = _parse_person_id(subj_iri)
                if pid is None:
                    # Not a person node (e.g. old marriage event node) — skip
                    i += 1
                    continue

                after_subj = block[block.find(">") + 1 :].strip()
                parts = _split_outside_quotes(after_subj, ";")
                parts = [_normalize_ws(p).rstrip(" .").strip() for p in parts if _normalize_ws(p).rstrip(" .").strip()]

                p = people.get(pid) or Person(pid=pid)
                for part in parts:
                    if part.startswith("rdf:type"):
                        if "ex:female" in part:
                            p.female = True
                        if "ex:male" in part:
                            p.female = False
                    elif part.startswith("ex:givenName"):
                        m = _LITERAL_RE.search(part)
                        if m:
                            p.given_name = _unescape_ttl_string(m.group(1))
                    elif part.startswith("ex:surname"):
                        m = _LITERAL_RE.search(part)
                        if m:
                            p.surname = _unescape_ttl_string(m.group(1))
                    elif part.startswith("rdfs:label"):
                        m = _LITERAL_RE.search(part)
                        if m:
                            p.full_name = _unescape_ttl_string(m.group(1))
                    elif part.startswith("ex:dateOfBirth"):
                        m = _DATE_TYPED_RE.search(part)
                        if m:
                            p.date_of_birth = m.group(1)
                    elif part.startswith("ex:dateOfDeath"):
                        m = _DATE_TYPED_RE.search(part)
                        if m:
                            p.date_of_death = m.group(1)
                people[pid] = p
                i += 1
                continue

            # Single-line triples: "<s> ex:parentOf <o> ."
            if line.startswith("<") and line.endswith("."):
                toks = line[:-1].strip().split()
                if len(toks) >= 3:
                    s_iri_m = _IRI_RE.match(toks[0])
                    p_tok = toks[1]
                    o_iri_m = _IRI_RE.match(toks[2])

                    if s_iri_m and o_iri_m:
                        s_pid = _parse_person_id(s_iri_m.group(1))
                        o_pid = _parse_person_id(o_iri_m.group(1))

                        if p_tok == "ex:parentOf" and s_pid is not None and o_pid is not None:
                            parent_of.add((s_pid, o_pid))
                        elif p_tok == "ex:marriedTo" and s_pid is not None and o_pid is not None:
                            married_to.add((s_pid, o_pid))
                i += 1
                continue

            i += 1

    return people, parent_of, married_to


def cypher_escape_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def emit_cypher(
    people: Dict[str, Person],
    parent_of: Set[Tuple[str, str]],
    married_to: Set[Tuple[str, str]],
    label: str = "",
) -> str:
    def pid_lit(pid: str) -> str:
        return f"'{cypher_escape_string(pid)}'"

    out: List[str] = ["// Generated by TTL2Cypher.py"]
    if label:
        out.append(f"// {label}")
    out += [
        "// Safe to re-run: uses MERGE for nodes and relationships",
        "",
        "// Constraints (Neo4j 5+ syntax).",
        "CREATE CONSTRAINT person_id IF NOT EXISTS FOR (p:Person) REQUIRE p.id IS UNIQUE;",
        "",
        "// Persons",
    ]

    for pid in sorted(people.keys()):
        p = people[pid]
        props: List[str] = [f"id: {pid_lit(pid)}"]
        if p.given_name is not None:
            props.append(f"givenName: '{cypher_escape_string(p.given_name)}'")
        if p.surname is not None:
            props.append(f"surname: '{cypher_escape_string(p.surname)}'")
        if p.full_name is not None:
            props.append(f"fullName: '{cypher_escape_string(p.full_name)}'")
        if p.female is not None:
            props.append(f"female: {str(bool(p.female)).lower()}")
            props.append(f"male: {str(bool(not p.female)).lower()}")
        if p.date_of_birth is not None:
            props.append(f"dateOfBirth: date('{p.date_of_birth}')")
        if p.date_of_death is not None:
            props.append(f"dateOfDeath: date('{p.date_of_death}')")
        out.append(f"MERGE (p:Person {{id: {pid_lit(pid)}}})")
        out.append(f"SET p += {{{', '.join(props)}}};")
    out.append("")

    out.append("// parentOf edges")
    for a, b in sorted(parent_of):
        out.append(f"MATCH (a:Person {{id: {pid_lit(a)}}}), (b:Person {{id: {pid_lit(b)}}})")
        out.append("MERGE (a)-[:PARENT_OF]->(b);")
    out.append("")

    out.append("// marriedTo edges")
    for a, b in sorted(married_to):
        out.append(f"MATCH (a:Person {{id: {pid_lit(a)}}}), (b:Person {{id: {pid_lit(b)}}})")
        out.append("MERGE (a)-[:MARRIED_TO]->(b);")
    out.append("")

    return "\n".join(out) + "\n"


def emit_csv_files(
    people: Dict[str, Person],
    parent_of: Set[Tuple[str, str]],
    married_to: Set[Tuple[str, str]],
) -> Dict[str, str]:
    """Return a dict of {filename: csv_content} for the three CSV files."""

    def make_csv(headers: List[str], rows: List[List[str]]) -> str:
        buf = io.StringIO()
        w = csv.writer(buf, lineterminator="\n")
        w.writerow(headers)
        w.writerows(rows)
        return buf.getvalue()

    person_rows = []
    for pid in sorted(people.keys()):
        p = people[pid]
        person_rows.append([
            pid,
            p.given_name  or "",
            p.surname     or "",
            p.full_name   or "",
            "true" if p.female is True  else ("false" if p.female is False else ""),
            "true" if p.female is False else ("false" if p.female is True  else ""),
            p.date_of_birth or "",
            p.date_of_death or "",
        ])

    edge_rows_po = [[a, b] for a, b in sorted(parent_of)]
    edge_rows_mt = [[a, b] for a, b in sorted(married_to)]

    return {
        "persons.csv":    make_csv(
            ["id", "givenName", "surname", "fullName", "female", "male", "dateOfBirth", "dateOfDeath"],
            person_rows,
        ),
        "parent_of.csv":  make_csv(["from_id", "to_id"], edge_rows_po),
        "married_to.csv": make_csv(["from_id", "to_id"], edge_rows_mt),
    }


def emit_load_cypher(
    batch_size: int = 500,
    *,
    prefix: str = "",
    header: str = "loadFromCSV.cypher",
    description: str = "Bulk-loads family tree data from CSV files into Neo4j.",
    include_constraint: bool = True,
) -> str:
    """Return the LOAD CSV Cypher script that reads the three CSV files.

    *prefix* is prepended to CSV filenames (e.g. "lastgen_" →
    "lastgen_persons.csv").  When loading incremental data the constraint
    already exists, so *include_constraint* can be set to False.
    """
    parts: List[str] = [
        f"// {header}",
        f"// {description}",
        "//",
        "// Paste each section into the Neo4j Browser and run in order.",
        "// Each section is a separate statement -- run them one at a time.",
        "//",
        "// Requires Neo4j 5.x+.",
    ]

    if include_constraint:
        parts += [
            "",
            "// -- Step 1: Constraint -------------------------------------------------------",
            "",
            "CREATE CONSTRAINT person_id IF NOT EXISTS FOR (p:Person) REQUIRE p.id IS UNIQUE;",
        ]

    parts += [
        "",
        f"// -- Load persons from {prefix}persons.csv ------------------------------------",
        "",
        f"LOAD CSV WITH HEADERS FROM 'file:///{prefix}persons.csv' AS row",
        f"CALL {{",
        f"  WITH row",
        f"  MERGE (p:Person {{id: row.id}})",
        f"  SET p.givenName = row.givenName,",
        f"      p.surname   = row.surname,",
        f"      p.fullName  = row.fullName,",
        f"      p.female    = (row.female = 'true'),",
        f"      p.male      = (row.male   = 'true'),",
        f"      p.dateOfBirth  = CASE WHEN row.dateOfBirth  <> '' THEN date(row.dateOfBirth)  ELSE null END,",
        f"      p.dateOfDeath  = CASE WHEN row.dateOfDeath  <> '' THEN date(row.dateOfDeath)  ELSE null END",
        f"}} IN TRANSACTIONS OF {batch_size} ROWS;",
        "",
        f"// -- Load PARENT_OF edges from {prefix}parent_of.csv --------------------------",
        "",
        f"LOAD CSV WITH HEADERS FROM 'file:///{prefix}parent_of.csv' AS row",
        f"CALL {{",
        f"  WITH row",
        f"  MATCH (a:Person {{id: row.from_id}})",
        f"  MATCH (b:Person {{id: row.to_id}})",
        f"  MERGE (a)-[:PARENT_OF]->(b)",
        f"}} IN TRANSACTIONS OF {batch_size} ROWS;",
        "",
        f"// -- Load MARRIED_TO edges from {prefix}married_to.csv ------------------------",
        "",
        f"LOAD CSV WITH HEADERS FROM 'file:///{prefix}married_to.csv' AS row",
        f"CALL {{",
        f"  WITH row",
        f"  MATCH (a:Person {{id: row.from_id}})",
        f"  MATCH (b:Person {{id: row.to_id}})",
        f"  MERGE (a)-[:MARRIED_TO]->(b)",
        f"}} IN TRANSACTIONS OF {batch_size} ROWS;",
        "",
    ]
    return "\n".join(parts) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="Convert family-tree TTL files into Neo4j Cypher (LPG).")
    ap.add_argument("--data-dir", type=str, required=True, help="Directory containing generated *.ttl files (e.g. out_graphdb/data)")
    ap.add_argument("--glob", dest="glob_pat", type=str, default="*.ttl", help="Glob pattern inside data-dir (default: *.ttl)")
    ap.add_argument("--out", type=str, default="-", help="Output file path (combined mode), output directory (split mode), or '-' for stdout")
    ap.add_argument("--split", action="store_true", help="Write one data-NNN.cypher per TTL file instead of one combined file. --out is treated as an output directory.")
    ap.add_argument("--csv", action="store_true", help="Also emit persons.csv, parent_of.csv, married_to.csv, and loadFromCSV.cypher to the --out directory.")
    ap.add_argument("--csv-exclude", type=str, nargs="*", default=[], metavar="FILE",
                    help="TTL filenames to exclude from CSV export (e.g. --csv-exclude 004.ttl). Cypher files are still generated for these.")
    args = ap.parse_args()

    data_dir = os.path.abspath(args.data_dir)
    ttl_paths = sorted(glob.glob(os.path.join(data_dir, args.glob_pat)))
    if not ttl_paths:
        raise SystemExit(f"No TTL files found in {data_dir!r} matching {args.glob_pat!r}")

    if args.split:
        out_dir = os.path.abspath(args.out) if args.out != "-" else data_dir
        os.makedirs(out_dir, exist_ok=True)
        for ttl_path in ttl_paths:
            stem = os.path.splitext(os.path.basename(ttl_path))[0]   # e.g. "000"
            out_path = os.path.join(out_dir, f"data-{stem}.cypher")
            people, parent_of, married_to = parse_ttl_files([ttl_path])
            cypher = emit_cypher(people, parent_of, married_to, label=f"Source: {os.path.basename(ttl_path)}")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(cypher)
            print(f"Wrote {out_path}  ({len(people)} people, {len(parent_of)} parentOf, {len(married_to)} marriedTo)")
    else:
        people, parent_of, married_to = parse_ttl_files(ttl_paths)
        cypher = emit_cypher(people, parent_of, married_to)
        if args.out == "-" or args.out.strip() == "":
            sys.stdout.write(cypher)
        else:
            out_path = os.path.abspath(args.out)
            os.makedirs(os.path.dirname(out_path), exist_ok=True)
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(cypher)
            print(f"Wrote Cypher to {out_path}")

    if args.csv:
        csv_dir = os.path.abspath(args.out) if args.out != "-" else data_dir
        os.makedirs(csv_dir, exist_ok=True)

        # --- Base CSV set (excludes *-lastgen.ttl files) ----------------------
        base_paths = [p for p in ttl_paths if "-lastgen" not in os.path.basename(p)]
        # Also honour --csv-exclude
        exclude_set = {os.path.basename(f) for f in args.csv_exclude}
        base_paths = [p for p in base_paths if os.path.basename(p) not in exclude_set]
        if exclude_set:
            print(f"CSV export: excluding {', '.join(sorted(exclude_set))}")

        all_people, all_parent_of, all_married_to = parse_ttl_files(base_paths)

        csv_files = emit_csv_files(all_people, all_parent_of, all_married_to)
        for fname, content in csv_files.items():
            fpath = os.path.join(csv_dir, fname)
            with open(fpath, "w", encoding="utf-8", newline="") as f:
                f.write(content)
            print(f"Wrote {fpath}")

        load_path = os.path.join(csv_dir, "loadFromCSV.cypher")
        with open(load_path, "w", encoding="utf-8") as f:
            f.write(emit_load_cypher())
        print(f"Wrote {load_path}")

        # --- Incremental CSV set (lastgen files only) -------------------------
        lastgen_paths = [p for p in ttl_paths if "-lastgen" in os.path.basename(p)]
        if lastgen_paths:
            inc_people, inc_parent_of, inc_married_to = parse_ttl_files(lastgen_paths)

            inc_csv_files = emit_csv_files(inc_people, inc_parent_of, inc_married_to)
            for fname, content in inc_csv_files.items():
                inc_fname = f"lastgen_{fname}"
                fpath = os.path.join(csv_dir, inc_fname)
                with open(fpath, "w", encoding="utf-8", newline="") as f:
                    f.write(content)
                print(f"Wrote {fpath}")

            inc_load_path = os.path.join(csv_dir, "loadIncrementalCSV.cypher")
            with open(inc_load_path, "w", encoding="utf-8") as f:
                f.write(emit_load_cypher(
                    prefix="lastgen_",
                    header="loadIncrementalCSV.cypher",
                    description="Loads the last-generation (incremental) data into Neo4j.",
                    include_constraint=False,
                ))
            print(f"Wrote {inc_load_path}")


if __name__ == "__main__":
    main()
